IF (WIN32)
  SET(CPACK_GENERATOR "ZIP")
  SET(CPACK_SOURCE_GENERATOR "ZIP")
ENDIF (WIN32)

IF (UNIX)
  SET(CPACK_GENERATOR "TGZ;DEB;RPM")
  SET(CPACK_SOURCE_GENERATOR "ZIP;TGZ;TBZ2")
ENDIF (UNIX)

SET(CPACK_STRIP_FILES "1")
SET(CPACK_PACKAGE_NAME "${PROJECT_NAME}")
SET(CPACK_PACKAGE_VENDOR "VLE Development Team")
SET(CPACK_PACKAGE_DESCRIPTION_SUMMARY "Python Package Virtual Laboratory Environment")
SET(CPACK_PACKAGE_CONTACT "Gauthier Quesnel <quesnel@users.sourceforge.net>")
SET(CPACK_PACKAGE_DESCRIPTION_FILE "${PROJECT_SOURCE_DIR}/README")
SET(CPACK_RESOURCE_FILE_LICENSE "${PROJECT_SOURCE_DIR}/COPYING")

IF ("${PYVLE_EXTRA}" STREQUAL "")
  SET(PYVLE_END "${PYVLE_PATCH}")
ELSE ("${PYVLE_EXTRA}" STREQUAL "")
  SET(PYVLE_END "${PYVLE_PATCH}-${PYVLE_EXTRA}")
ENDIF ("${PYVLE_EXTRA}" STREQUAL "")

SET(CPACK_PACKAGE_VERSION_MAJOR "${PYVLE_MAJOR}")
SET(CPACK_PACKAGE_VERSION_MINOR "${PYVLE_MINOR}")
SET(CPACK_PACKAGE_VERSION_PATCH "${PYVLE_END}")

SET(CPACK_SOURCE_PACKAGE_FILE_NAME "${PYVLE_NAME}")
SET(CPACK_SOURCE_IGNORE_FILES "\\\\.swp$;/\\\\.gitignore;/build/;/lib/;/\\\\.git/")

SET(CPACK_DEBIAN_PACKAGE_NAME ${PYVLE_NAME}-${PYVLE_MAJOR}.${PYVLE_MINOR})
SET(CPACK_DEBIAN_PACKAGE_VERSION ${PYVLE_MAJOR}.${PYVLE_MINOR}.${PYVLE_END})
SET(CPACK_DEBIAN_PACKAGE_MAINTAINER "Gauthier Quesnel <quesnel@users.sourceforge.net>")
SET(CPACK_DEBIAN_PACKAGE_DESCRIPTION "VLE, a framework for multi-modeling, simulation and analysis of complex dynamical systems.")
SET(CPACK_DEBIAN_PACKAGE_SECTION "libs")
SET(CPACK_DEBIAN_PACKAGE_PRIORITY "extra")

SET(CPACK_RPM_PACKAGE_SUMMARY "VLE, a framework for multi-modeling, simulation and analysis of complex dynamical systems.")
SET(CPACK_RPM_PACKAGE_NAME ${PYVLE_NAME})
SET(CPACK_RPM_PACKAGE_VERSION ${PYVLE_MAJOR}.${PYVLE_MINOR}.${PYVLE_END})
SET(CPACK_RPM_PACKAGE_RELEASE "1")
SET(CPACK_RPM_PACKAGE_VENDOR "Gauthier Quesnel <quesnel@users.sourceforge.net>")
SET(CPACK_RPM_PACKAGE_LICENSE "GNU General Public License (GPL)")
SET(CPACK_RPM_PACKAGE_DESCRIPTION "VLE, a framework for multi-modeling, simulation and analysis of complex dynamical systems.")

INCLUDE(CPack)

# vim:tw=0:ts=8:tw=0:sw=2:sts=2
